catalog/urls.py
from catalog import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),     # name 参数用于反向解析 即：<a href="{% url 'books' %}">Books</a>   url 'books' ---> /catalog/books/指代这个

    path('books/', views.BookListView.as_view(), name='books'),   # 将一个基于类的视图BookListView， 转换为Django能调用的视图函数.as_view()
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),   # <int:pk>捕获book id，并令pk=book id传递给视图作为参数

    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedBooksListView.as_view(), name='all_borrowed_books'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name = 'renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete', views.AuthorDelete.as_view(), name = 'author_delete'),
    path('book/create/', views.BookCreate.as_view(), name = 'book_create'),
    path('book/<int:pk>/update', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete', views.BookDelete.as_view(), name = 'book_delete'),

]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf.urls.static import static    # 配置静态文件服务：如图片，CSS， js等静态文件
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),   # include("catalog.urls") 会导入 catalog 应用的 urls 进行进一步的路由
    path('', RedirectView.as_view(url='/catalog/')),    # 重定向如：输入：http://127.0.0.1:8000/，识别后重定向为 http://127.0.0.1:8000/catalog/ 然后又重定向为 catalog.urls继续后续域名匹配
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.urls import reverse
import uuid  # Required for unique book instances
from django.db import models
from django.db.models.functions import Lower
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

# 这部分是教程测试时使用的
# class MyModelName(models.Model):
#     # Fields
#     my_field_name = models.CharField(max_length=20, help_text="Enter field name")
#
#     # Metadata
#
#     class Meta:
#         ordering=['-my_field_name']   # 如果没有按order_by()检索那么，默认按my_field_name倒叙为顺序输出
#
#
#     # Methods
#     def __str__(self):
#         return self.my_field_name


class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """

    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre(e.g. Science Fiction, French Poetry etc.)")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                Lower("name"),
                name='genre_name_case_insensitive_unique',
                violation_error_message = "Genre already exists (case insensitive match)"
            )
        ]

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

    def get_absolute_url(self):
        return reverse("genre-detail", args=[self.id])


class Language(models.Model):
    """
    Model representing a book language.
    """
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)",
    )

    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


    class Meta:
        constraints = [
            models.UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message="Language already exists (case insensitive match)"
            )
        ]




class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)   # 当外键指向的author对象被删除时，引用它的记录字段（这里是ForeignKey）会被自动设为NULL

    summary = models.TextField(blank=True, null=True, max_length=1000,
                               help_text="Enter a brief description of the book")
    isbn = models.CharField("ISBN", max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'author']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])  # 根据路由名字book-detail反向生成URL + args

    def display_genre(self):     # 用于显示genre（多对多情况下）正常不能显示在Book管理界面下的情况
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])      # self.genre.all()[:3]找到对应实例的genre，然后拼接成字符串就可以使用了

    display_genre.short_description = 'Genre'    # 定义该方法的域字段名（列表头名）


    # def display_Language(self):
    #     return str(self.)
    # display_Language.short_description = 'Language'

class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")

    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),    # 数据库存 'm'，界面显示 Maintenance
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              default='m', blank=True, help_text="Book availability")

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)     # 给表bookinstance添加一个权限，除了增删改查还可以 can_mark_returned（但显示选项是"Set book as returned"），没有实际作用也就是可以做身份识别，可能后续基于此身份识别可以做相应的功能

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return '%s (%s)' % (self.id, self.book.title)





class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null = True, blank=True)
    date_of_death = models.DateField(null = True, blank=True)


    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, %s' %(self.last_name, self.first_name)

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime #for checking renewal date range.

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        date = self.cleaned_data['renewal_date']    # post过来的数据都是得先清洗为python格式然后放入cleaned_data字典里

        #Check date is not in past.
        if date < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if date > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return date

catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, Author, BookInstance, Genre

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.conf import settings

from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from .forms import  RenewBookForm
from django.contrib.auth.decorators import permission_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


# Create your views here.


def index(request):
    """
    View function for home page of site.
    """

    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()


    '''
    num_instances = BookInstance.objects.all().count() 效果上等于 num_instances = BookInstance.objects.count()
    '''

    num_instances_maintenance = BookInstance.objects.filter(status__exact='m').count()
    num_instances_on_loan = BookInstance.objects.filter(status__exact='o').count()
    num_instances_reserved = BookInstance.objects.filter(status__exact='r').count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()

    print("DB PATH:", settings.DATABASES["default"]["NAME"])

    return render(
        request,
        'index.html',
        context={
            'num_books':num_books,
            'num_instances':num_instances,
            'num_instances_available':num_instances_available,
            'num_instances_on_loan': num_instances_on_loan,
            'num_instances_reserved': num_instances_reserved,
            'num_instances_maintenance': num_instances_maintenance,
            'num_authors':num_authors,
            'num_visits': num_visits,
            'test': request.session['num_visits'],
        }
    )

@permission_required('catalog.can_mark_returned')   # 只有授权用户才可以访问它
def renew_book_librarian(request, pk):
    """
        View function for renewing a specific BookInstance by librarian
    """
    book_inst = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all_borrowed_books'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date, })

    return render(
        request,
        'book_renew_librarian.html',
        {'form': form, 'bookinst': book_inst})

class BookListView(generic.ListView):    # 基于类的通用列表视图, 类似于模板
    model = Book
    queryset = Book.objects.all()

    context_object_name = "book_list"

    template_name = 'books_list.html'

    paginate_by = 2 # 只要超过10条记录，视图就会开始对它发送到模板的数据，进行分页， 可以使用 URL：/catalog/books/?page=2访问


class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing books on loan to current user.
    """
    model = BookInstance
    queryset = BookInstance.objects.all()
    context_object_name = "bookinstance_list"
    template_name ='bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class BorrowedBooksListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'borrowed_books_list.html'
    context_object_name = 'borrowed_books'

    # 限制用户必须拥有 can_mark_returned 权限才能访问
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        """返回所有借阅的书本，包含借用人的名字"""
        return BookInstance.objects.filter(status='o').select_related('borrower')

class BookDetailView(generic.DetailView):  # 基于类的通用详情信息视图，类似于模板
    model =Book
    template_name = 'book_detail.html'



class AuthorListView(generic.ListView):
    model = Author
    queryset = Author.objects.all()
    context_object_name = "author_list"
    template_name = 'author_list.html'

class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'


class AuthorCreate(PermissionRequiredMixin, CreateView):   # 先get获得一个表单填写，然后再post原URL修改数据库内容并重定向到author detail页面
    permission_required = 'catalog.can_mark_returned'
    model = Author
    fields = '__all__'
    initial={'date_of_death':'3000-05-01 ',}
    template_name = 'author_form.html'

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']
    permission_required = 'catalog.can_mark_returned'
    template_name = 'author_form.html'

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.can_mark_returned'
    template_name = 'author_confirm_delete.html'


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    permission_required='catalog.can_mark_returned'
    template_name = 'book_form.html'

class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = ['author', 'summary', 'isbn', 'genre', 'language']
    permission_required='catalog.can_mark_returned'
    template_name = 'book_form.html'

class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    permission_required='catalog.can_mark_returned'
    template_name = 'book_confirm_delete.html'
    success_url = reverse_lazy('books')

catalog/templates/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Author</h1>

  <p>Are you sure you want to delete the author: {{ author }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
  </form>
{% endblock %}

catalog/templates/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }}, {{author.last_name}}</h1>
    <h2>{% if author.date_of_birth%}
        {{author.date_of_birth }}{% endif %}
        {% if author.date_of_birth or author.date_of_death%} - {% endif %}
        {%if author.date_of_death%}
        {{ author.date_of_death}} {% endif %}
    </h2>
    <div style="margin-left:20px;margin-top:20px">
        <h2>Books:</h2>
        {% for book in author.book_set.all %}
            <a href="{% url 'book-detail' book.pk%}"><strong>{{ book.title }}</strong></a>
            <p>{{ book.summary }}</p>
        {% endfor %}
    </div>



{% endblock %}

catalog/templates/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>

  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          <a href="{{ author.get_absolute_url }}">{{ author.first_name }}, {{author.last_name}}</a>
          ({{author.date_of_birth}} - {{author.date_of_death}})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

catalog/templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap 3 -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          <ul class="sidebar-nav">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'books' %}">All books</a></li>
            <li><a href="{% url 'authors' %}">All authors</a></li>

            {% if user.is_authenticated %}
              <li>User: {{ user.get_username }}</li>
              <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>

              <li>
                <form method="post" action="{% url 'logout' %}?next={{ request.path }}">
                  {% csrf_token %}
                  <button
                    type="submit"
                    style="background:none;border:none;padding:0;color:#0d6efd;cursor:pointer;"
                  >
                    Logout
                  </button>
                </form>
              </li>

              {% if perms.catalog.can_mark_returned %}
                <li><hr></li>
                <li><strong>Staff</strong></li>
                <li><a href="{% url 'all_borrowed_books' %}">All borrowed</a></li>
                <li><a href="{% url 'author_create' %}">Create Author</a></li>
                <li><a href="{% url 'book_create' %}">Create Book</a></li>
              {% endif %}

            {% else %}
              <li>
                <a href="{% url 'login' %}?next={{ request.path }}">Login</a>
              </li>
            {% endif %}
          </ul>
          {% endblock %}
        </div>

        <div class="col-sm-10">
          {% block content %}{% endblock %}

          {% block pagination %}
            {% if is_paginated %}
              <div class="pagination">
                <span class="page-links">
                  {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}

                  <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>

                  {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
                </span>
              </div>
            {% endif %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

catalog/templates/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Book</h1>

  <p>Are you sure you want to delete the Book: {{ book.title }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
  </form>
{% endblock %}

catalog/templates/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk%}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    <!-- 虽然Book里面没有bookinstance但是bookinstance_set Django提供了自动构建反向查找的函数-->
    <!-- 即在Book model里面创建bookinstance_set()函数-->
    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{bookinst.book.title}}</h1>
  <p>Borrower: {{bookinst.borrower}}</p>
  <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>
            Due date: {{bookinst.due_back}}
  </p>

  <form action="" method="post"> <!-- action为空说明此表单提交会提交到当前URL路径  -->
    {% csrf_token %}
    <table>
      {{ form }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/books_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>

  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/borrowed_books_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>All Borrowed Books</h1>
  <ul>
    {% for bookinst in borrowed_books %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="url book-detail bookinst.book.pk">{{ bookinst.book.title }}</a>
          ({{ bookinst.due_back }}) - Borrowed by: {{ bookinst.borrower.get_full_name }}
      </li>
    {% empty %}
      <li>No borrowed books found.</li>
    {% endfor %}
  </ul>
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

  <h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Copies on loan:</strong> {{ num_instances_on_loan }}</li>
    <li><strong>Copies reserved:</strong> {{ num_instances_reserved }}</li>
    <li><strong>Copies maintenance:</strong> {{ num_instances_maintenance }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

  <p>
  You have visited this page {{ num_visits }}{% if num_visits == 1 %} time {% else %} times{% endif %}.
  </p>


{% endblock %}